version: "3"
services:
  node1:
    networks:
      - app-network
    container_name: "node1"
    build:
      context: ./server1
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  node1_1:
    networks:
      - app-network
    container_name: "node1_1"
    build:
      context: ./server1
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
  node2:
    networks:
      - app-network
    container_name: "node2"
    build:
      context: ./server2
      dockerfile: Dockerfile
    ports:
      - "8002:8000"

  node2_1:
    networks:
      - app-network
    container_name: "node2_1"
    build:
      context: ./server2
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
  redis:
    image: redis
    networks:
      - app-network
    ports:
      - "6380:6379"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - node1
      - node1_1
      - node2
      - node2_1

networks:
  app-network:
    driver: bridge
