version: "3"
services:
  redis:
    container_name: redis
    networks:
      - app-network
    image: redis
    ports:
      - "6379:6379"
  node1:
    networks:
      - app-network
    container_name: "node1"
    build:
      context: ./server1
      dockerfile: Dockerfile
    volumes:
      - ./server1/uploads:/usr/src/app/uploads
    ports:
      - "8000:8000"
  node1_1:
    networks:
      - app-network
    container_name: "node1_1"
    build:
      context: ./server1
      dockerfile: Dockerfile
    volumes:
      - ./server1/uploads:/usr/src/app/uploads
    ports:
      - "8001:8000"
  node2:
    networks:
      - app-network
    container_name: "node2"
    build:
      context: ./server2
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - node1
      - node1_1
      - node2

networks:
  app-network:
    driver: bridge
